<?php
	define("DB_HOST","localhost");
	define("DB_USER","cccph");
	define("DB_PASS","ccc");
	define("DB_NAME","news_offline");
	define("DB_IPADDRESS","localhost");
	define("DB_VERSION","v2.0");
	define("APP","ODESv3.0");
?>